[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri", "./src", "./static"]

[serve]
address = "0.0.0.0"
port = 1420
open = false
ws_protocol = "ws"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i static/assets/css/main.css -o dist/main.css"]
